# Generated by Django 5.2.7 on 2025-12-02 09:54

from django.db import migrations


def create_public_room(apps, schema_editor):
    ChatRoom = apps.get_model('chat', 'ChatRoom')
    ChatRoom.objects.get_or_create(name='public')

class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_public_room),
    ]
